env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - "./tsconfig.json"
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - prettier
  - simple-import-sort
  - unused-imports
rules:
  "react/jsx-filename-extension":
    - "error"
    - "extensions":
        - ".tsx"
        - ".ts"
  "react/jsx-uses-react": "off" # no longer needed for React 17
  "react/react-in-jsx-scope": "off" # no longer needed for React 17
  "prettier/prettier": "error"
  "@typescript-eslint/no-unused-vars": "warn"
  "simple-import-sort/imports": "error"
  "simple-import-sort/exports": "error"
  "import/first": "error"
  "import/newline-after-import": "error"
  "import/no-duplicates": "error"
  "unused-imports/no-unused-imports": "error"
